language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

jobs:
  include:
    - stage: Publish
      rust: stable
      script: echo "Publishing to crates.io ..."
      deploy:
        provider: script
        script:
         - cargo login $CRATES_TOKEN
         - cargo publish
        on:
          tags: true